#!/usr/bin/env sh

case "$(uname)" in
    CYGWIN*) DIRNAME=$(cygpath -d "$(dirname "$(readlink -f "$0")")");;
    Darwin*) DIRNAME=$(dirname "$(readlink "$0")");;
    *) DIRNAME=$(dirname "$(readlink -f "$0")");;
esac
if [ "$DIRNAME" = "." ]; then
    DIRNAME="$(dirname "$0")"
fi

## Jar from 'gradle jar'
java -jar "${DIRNAME}/build/libs/fbSAT-1.0.jar" $*

## Artifact from IDEA
# java -jar "${DIRNAME}/out/artifacts/fbSAT.jar" $*
